# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GsVS9BFzBo5lqmuoIYjjHiON9cC7brdg
"""



print ("helloworld")